version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - '27017'
    ports:
      - "27017:27017"
    command: '--smallfiles --logpath=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
    links:
      - mongo:mongo
volumes:
  data-volume: